# -*- coding: utf-8 -*-
"""catboost.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W9pEPS5NEO4JTxMukkIMPGcHl1TqyICs
"""

!pip install catboost

import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error
from catboost import CatBoostRegressor

df = pd.read_csv('viscoo.csv')

X = df[['x1', 'x2']]
y = df['visc']

y_pred = np.zeros(len(y))
y_actual = np.zeros(len(y))

regr = CatBoostRegressor(n_estimators=10, max_depth=5, random_state=34, verbose=True)

for i in range(len(X)):
    # Get the index of the left-out sample
    left_out_index = i
    
    # Split the data into training set (all samples except left-out sample) and test set (left-out sample)
    X_train = X.drop(index=left_out_index)
    y_train = y.drop(index=left_out_index)
    X_test = X.loc[[left_out_index]]
    
    # Fit the model on training data and predict the left-out sample
    regr.fit(X_train, y_train)
    y_pred[i] = regr.predict(X_test)
    y_actual[i] = y.loc[left_out_index]

print("Mean square error train:", mean_squared_error(y, y_pred))

print("Mean absolute error train:", mean_absolute_error(y, y_pred))

print("Y Actual:", y_actual)

print("Y Predicted:", y_pred)